version: 2.1

jobs:
  build:
    working_directory: ~/monolith-to-microservices

    docker:
      - image: circleci/node:14

    steps:

      - checkout

      - run:
          name: Check versions
          command: |
            docker --version
            docker-compose --version

      - run:
          name: Build images
          command: |
            docker-compose -f docker-compose-build.yaml build --parallel
            docker tag udagram-frontend udacityclouddeveloper/udagram-frontend
            docker tag udagram-api-feed udacityclouddeveloper/udagram-api-feed
            docker tag udagram-api-user udacityclouddeveloper/udagram-api-user
            docker tag udagram-reverseproxy udacityclouddeveloper/udagram-reverseproxy

workflows:
  build-and-test:
    jobs:
      - build



