version: 2.1
jobs:
  build-api-feed:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
        command: |
        cd udagram-api-feed
        npm install
        npm run build
workflows:
  build-and-test:
    jobs:
      - build-api-feed
