version: 2.1
jobs:
  build-api-feed:
    docker:
      - image: cimg/base:2022.09
    working_directory: ~/project/udagram-api-feed
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t udacityclouddeveloper/udagram-api-feed
  
workflows:
  build-and-test:
    jobs:
      - build-api-feed
