version: 2.1
jobs:
  mybuildjob:
    docker:
      - image: docker/compose:1.29.1
    steps:
      - checkout
      - run:
          name: build and push
          command: |
            docker-compose -f docker-compose-build.yaml build --parallel

workflows:
  build_and_push:
    jobs:
      - mybuildjob