version: 2.1
jobs:
  build-frontend:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
        name: "Build frontend"
        command: |
          cd udagram-frontend
          npm install
          npm run build
workflows:
  build-and-test:
    jobs:
      - build-frontend
