version: 2.1
jobs:
  build-api-feed:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          cd udagram-api-feed
      - run:
          docker build -t udacityclouddeveloper/udagram-api-feed:latest .
  
workflows:
  build-and-test:
    jobs:
      - build-api-feed
