version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node14
    steps:
      - checkout
      - run: docker-compose -f docker-compose-build.yaml build --parallel
      - run: docker-compose up