version: 2.1
jobs:
  build-api-feed:
    working_directory: ~/project/udagram-api-feed
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
            docker build -t udacityclouddeveloper/udagram-api-feed .
  
workflows:
  build-and-test:
    jobs:
      - build-api-feed
