version: 2.1
jobs:
  build-frontend:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - commmand: cd udagram-frontend
      - run: npm install
      - run: npm run build
workflows:
  build-and-test:
    jobs:
      - build-frontend
