apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: example-configmap
                key: POSTGRES_HOST
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: example-configmap
                key: URL
        image: mssdc/udagram-reverseproxy:v1
        ports:
        - containerPort: 8080