apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100
    protocol: TCP
  selector:
    service: frontend