apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: example-configmap
                key: POSTGRES_HOST
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: example-configmap
                key: URL
        image: mssdc/udagram-frontend:v1
        ports:
        - containerPort: 80




