apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: example-configmap
                key: POSTGRES_HOST
        image: mssdc/udagram-api-feed:v2
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: my-secret