apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    service: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: backend-user
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - name: backend-user
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"    
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: example-configmap
                key: POSTGRES_HOST
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: example-configmap
                key: URL
        image: mssdc/udagram-api-user:v1
      imagePullSecrets:
      - name: my-secret