name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
  
      - uses: actions/checkout@v4
      
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: docker-hub-repo/udagram-api-feed
          registry: docker.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
            

  







          

