name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: build an push udagram-api-feed
        uses: actions/checkout@v4
        
      - run: |
            cd udagram-api-feed
            docker build . -t udacityclouddeveloper/udagram-api-feed:latest

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}

      - run: |
            docker push ${{ secrets.USER }}/udagram-api-feed:latest





      

 
  







          

