name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with: 
        image: udacityclouddeveloper/udagram-api-feed
        registry: docker.io
        username: ${{ secrets.USERNAME }}
        passwoird: ${{ secrets.PASSWORD }}

        

