name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: build image
        run: |
            cd udagram-api-feed
            docker build . -t udacityclouddeveloper/udagram-api-feed:latest

      - name: push to docker
        env:
          USER: ${{ env.USER }}
          TOKEN: ${{ env.TOKEN }}
        run: |
            docker login -u ${{ secrets.USER }} -p ${{ secrets.TOKEN }}
            docker push udacityclouddeveloper/udagram-api-feed:latest
      

 
  







          

